name: plan-on-gchat
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Start GChat server
        uses: ./__fixtures__/gchat-server

      - name: Plan release
        uses: ./plan-on-gchat
        with:
          gchat-webhook-url: ${{ env.GCHAT_WEBHOOK_URL }}
          version: "1.2.4"
          version-date: "2025-06-01"
          project-name: spring-boot
