name: status-on-gchat
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Start GChat server
        uses: ./__fixtures__/gchat-server

      - name: Start GitHub server
        uses: ./__fixtures__/github-server
        with:
          port: "18082"

      - name: Send workflow status
        uses: ./status-on-gchat
        with:
          gchat-webhook-url: ${{ env.GCHAT_WEBHOOK_URL }}
