name: update-learn-page-api
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Start Spring Projects server
        uses: ./__fixtures__/spring-projects-server

      - name: Create releases
        uses: ./update-learn-page
        with:
          version: "1.2.3"
          project-name: owner/spring-boot
          projects-api-base: ${{ env.PROJECTS_API_BASE }}

      - name: Update releases
        uses: ./update-learn-page
        with:
          version: "1.2.4"
          project-name: owner/spring-boot
          projects-api-base: ${{ env.PROJECTS_API_BASE }}
