name: "compute-next-scheduled-milestone"
description: "An action that computes the next scheduled milestone for the given version generation"
author: "jzheaux"

inputs:
  snapshot-version:
    description: "The current project SNAPSHOT version"
    required: true
  milestone-token:
    description: "The token needed to query project milestone information"
    required: false

  milestone-repository:
    description: "The repository to query project milestone information"
    required: false

outputs:
  release-version:
    description: "The project's next scheduled release version"
  days-til-release:
    description: "The number of days until the next scheduled release; 0 if the release is today"

runs:
  using: "node24"
  main: '../dist/compute-next-scheduled-milestone/main/index.js'
