name: "push-release-version"
description: "Push release version"
author: "jzheaux"

inputs:
  version:
    description: "The version number to use"
    required: true

runs:
  using: "composite"
  steps:
  - name: Set Version on Project
    shell: bash
    env:
      VERSION: ${{ inputs.version }}
    run: |
      if test -f pom.xml
      then
        mvn versions:set -DnewVersion=$VERSION -DgenerateBackupPoms=false -DprocessAllModules=true -B -ntp
      else
        sed -i "s/version=.*/version=$VERSION/" gradle.properties
      fi
  - name: Commit Version
    shell: bash
    env:
      VERSION: ${{ inputs.version }}
    run: |
      git config user.name 'github-actions[bot]'
      git config user.email 'github-actions[bot]@users.noreply.github.com'
      git commit -am "Release $VERSION"
      git push