name: "Release - Perform Release"

permissions:
  contents: write
  issues: write

on:
  workflow_dispatch:

jobs:
  planner:
    name: "Is there a release that is ready today?"
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.release-version.outputs.release-version }}
      should-release: ${{ steps.release-version.outputs.release-version != '' && steps.release-version.outputs.days-til-release == '0' && steps.count-issues.outputs.count == '0' }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - id: release-version
        uses: ./compute-next-scheduled-milestone
        with:
          milestone-token: ${{ github.token }}
          snapshot-version: ${{ github.ref_name }}
      - if: ${{ steps.release-version.outputs.release-version != '' && steps.release-version.outputs.days-til-release == '0' }}
        id: count-issues
        uses: ./count-open-issues
        with:
          milestone: ${{ steps.release-version.outputs.release-version }}

  publish-release-notes:
    name: "Publish Release Notes"
    needs: planner
    if: ${{ needs.planner.outputs.should-release == 'true' }}
    uses: ./.github/workflows/release-publish-release-notes.yml
    with:
      version: ${{ needs.planner.outputs.release-version }}
    secrets: inherit

  schedule-milestones:
    name: "Schedule Milestones"
    needs: [planner, publish-release-notes]
    if: ${{ needs.planner.outputs.should-release == 'true' }}
    uses: ./.github/workflows/release-schedule-milestones.yml
    with:
      version: ${{ needs.planner.outputs.release-version }}
    secrets: inherit

  announcements:
    name: "Announcements"
    needs: [planner, schedule-milestones]
    if: ${{ needs.planner.outputs.should-release == 'true' }}
    uses: ./.github/workflows/release-announcements.yml
    with:
      version: ${{ needs.planner.outputs.release-version }}
    secrets: inherit