name: "compute-artifact-repository"
description: "An action that determines the deployment repository URI and name"
author: "jzheaux"
inputs:
  version:
    description: "The version to deploy"
    required: true
  repository:
    description: "The project's repository; uses the current repository by default"
    required: false
    default: ${{ github.repository }}

outputs:
  uri:
    description: "The artifact repository URI"
    value: ${{ steps.commercial-repository-uri.outputs.result || steps.oss-repository-uri.outputs.result }}
  name:
    description: "The artifact repository name"
    value: ${{ steps.commercial-repository-name.outputs.result || steps.oss-repository-name.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: Is Commercial?
      id: is-commercial
      shell: bash
      env:
        REPOSITORY: ${{ inputs.repository }}
      run: |
        if [[ $REPOSITORY == *"-commercial" ]] ; then
          echo "result=true" >> $GITHUB_OUTPUT
        else
          echo "result=false" >> $GITHUB_OUTPUT
        fi
    - name: Compute the Commercial Artifact Repository URI
      id: commercial-repository-uri
      if: ${{ steps.is-commercial.outputs.result == 'true' }}
      shell: bash
      run: |
        echo "result=https://usw1.packages.broadcom.com" >> $GITHUB_OUTPUT
    - name: Compute the Commercial Artifact Repository Name
      id: commercial-repository-name
      if: ${{ steps.is-commercial.outputs.result == 'true' }}
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: |
        if [[ $VERSION == *"-SNAPSHOT" ]] ; then
          echo "result=spring-enterprise-maven-dev-local" >> $GITHUB_OUTPUT
          exit 0;
        fi
        if [[ $VERSION == *"-RC"* ]] ; then
          echo "result=spring-enterprise-maven-stage-local" >> $GITHUB_OUTPUT
          exit 0;
        fi
        if [[ $VERSION == *"-M"* ]] ; then
          echo "result=spring-enterprise-maven-stage-local" >> $GITHUB_OUTPUT
          exit 0;
        fi
        echo "result=spring-enterprise-maven-prod-local" >> $GITHUB_OUTPUT
    - name: Compute the OSS Artifact Repository URI
      id: oss-repository-uri
      if: ${{ steps.is-commercial.outputs.result == 'false' }}
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: |
        if [[ $VERSION == *"-SNAPSHOT" ]] ; then
          echo "result=https://repo.spring.io" >> $GITHUB_OUTPUT
          exit 0;
        fi
        echo "result=central" >> $GITHUB_OUTPUT
    - name: Compute the OSS Artifact Repository Name
      id: oss-repository-name
      if: ${{ steps.is-commercial.outputs.result == 'false' }}
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: |
        if [[ $VERSION == *"-SNAPSHOT" ]] ; then
          echo "result=libs-snapshot-local" >> $GITHUB_OUTPUT
          exit 0;
        fi
        echo "result=central" >> $GITHUB_OUTPUT